<?php echo $this->action( 'paginator', 'vaga', 'default' ); ?>

<script type="text/javascript">
    $( '#mais-vagas' ).live( 'click', 
	function( e )
	{
	    e.stopPropagation();
	    
	    var p = $(this).attr( 'data-page' );
	    
	    $.mobile.showPageLoadingMsg();
	    
	    $.ajax(
		{
		    url: baseUrl + 'vaga/paginator/p/' + p,
		    complete: function()
		    {
			$.mobile.hidePageLoadingMsg();
		    },
		    success: function( data ) 
		    {    
			var snippet = $( data ).find( '#list-vagas' ).html();
			
			$( '#content #list-vagas' ).append( snippet ).listview( 'refresh' )
			$( '#content #list-vagas .collapsed-item' ).collapsible();
			
			if ( $(data).find( '#mais-vagas' ).length > 0 )
			    $( '#content #mais-vagas' ).attr( 'data-page', $(data).find( '#mais-vagas' ).eq( 0 ).attr( 'data-page' ) );
			else
			    $( '#content #mais-vagas' ).remove();
		    }
		}
	    );
	}
    );
</script>