<?php if ( $this->avisos->count() < 1 ) : ?>

    <ul data-role="listview" data-inset="true">
	<li data-theme="c">
	    Não foram encontrados avisos
	</li>
    </ul>

<?php else : ?>

    <ul data-role="listview" data-inset="true" id="list-avisos">
	<?php foreach ( $this->avisos as $data => $avisos ) : ?>
		<!--
	    <li data-role="list-divider">
		<?php //echo $this->date( $data, "EEEE, dd 'de' MMMM 'de' yyyy." ); ?>
		
		<span class="ui-li-count">
		    <?php //echo count( $avisos ); ?>
		</span>
		
	    </li>
	    -->
	    <?php foreach ( $avisos as $aviso ) : ?>
		<li data-theme="<?php echo empty( $aviso['urgente'] ) ? '' : 'c'; ?>">
		    <a href="<?php echo $this->url( array( 'action' => 'read', 'id' => $aviso['codigo'] ) ); ?>">
			<?php echo $aviso['titulo']; ?>
		    </a>
		</li>
	    <?php endforeach; ?>
	<?php endforeach; ?>
    </ul>

    <?php if ( !empty( $this->more ) ) : ?>
	<a data-role="button" data-page="<?php echo ++$this->page; ?>" data-shadow="false" id="mais-anuncio" href="javascript:;">Mais..</a>
    <?php endif; ?>

<?php endif; ?>